### ISSUE TITLE
Create winget package

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/winget-metanorma#1]

**Comment by CAMOBAP** [comment]
The first package was released on Winget https://github.com/microsoft/winget-pkgs/pull/168143#event-14018677917

It makes sense to automate workflow for PR creation on packed-mn is released

**Comment by CAMOBAP** [comment]
@ronaldtse it looks like org-level secrets are not accessible in fork https://github.com/metanorma/winget-pkgs that I create

I mean `secrets.METANORMA_CI_PAT_TOKEN`

could you please help make them visible for `metanorma/winget-pkgs`

**Comment by CAMOBAP** [comment]
Still the case https://github.com/metanorma/winget-metanorma/actions/runs/10884201320/job/30198979973

**Comment by CAMOBAP** [comment]
It works now, but I have issues with creation of automated PRs

Manual this time https://github.com/microsoft/winget-pkgs/pull/192060

Related issue https://github.com/peter-evans/create-pull-request/issues/2021 `peter-evans/create-pull-request@v5` isn't good for this 

Will make separate issue for this, for now this workflow do:
- sync with upstream
- push the changes

The last step is create PR which is not automated
